/**
 * Full UVeye damage / detection `checkType` catalog for manual “missed damage” entry.
 * Sourced from org check configuration (Body + Tire + Undercarriage). Excludes `BodyPart*`
 * rows — those are surface/part wiring, not damage kinds; car part is chosen separately.
 * Enable/disable in UVeye is ignored here so reviewers always see every possible type label.
 */
export const UVeye_CATALOG_DAMAGE_CHECK_TYPES: readonly string[] = [
  // Body — damage / condition (not BodyPart*)
  'BodyBigDent',
  'BodyBrokenLicensePlate',
  'BodyBrokenPart',
  'BodyBubbleDent',
  'BodyBubblePinchDent',
  'BodyBubbleZigzagDent',
  'BodyChip',
  'BodyClusterDent',
  'BodyCrack',
  'BodyCustom',
  'BodyDamage',
  'BodyDamageBox',
  'BodyDent',
  'BodyDentWithPaintDamage',
  'BodyDentWithoutPaintDamage',
  'BodyGlassesDent',
  'BodyHailDamage',
  'BodyHangingObject',
  'BodyLongScratch',
  'BodyLoose',
  'BodyManualFix',
  'BodyMissingPart',
  'BodyMissingTowCover',
  'BodyPaintchip',
  'BodyPaintDamage',
  'BodyRust',
  'BodyScratch',
  'BodySevereDamage',
  'BodySevereScratch',
  'BodyShallowDent',
  'BodyShallowScratch',
  'BodySunDamage',
  // Tires
  'TireAge',
  'TireBrand',
  'TireBrokenBelt',
  'TireBulge',
  'TireCosmeticRimDamage',
  'TireCustom',
  'TireDamage',
  'TireForeignObject',
  'TireHazardRimDamage',
  'TireLugNut',
  'TireMismatch',
  'TireMissingLugNut',
  'TireMissingLugNutCover',
  'TireMudAndSnow',
  'TirePressure',
  'TireRimDamage',
  'TireSize',
  'TireSpeedAndLoad',
  'TireTreadDepth',
  'TireTreadManualMeasurement',
  'TireUnevenTreadsWear',
  'TireWear',
  // Undercarriage
  'UndercarriageBrokenExhaust',
  'UndercarriageBrokenShield',
  'UndercarriageBumperDamage',
  'UndercarriageCustom',
  'UndercarriageDamage',
  'UndercarriageForeignObject',
  'UndercarriageHandWriting',
  'UndercarriageLeak',
  'UndercarriageMinorLeak',
  'UndercarriageMissingCatalyticConverter',
  'UndercarriageRearLeak',
  'UndercarriageRust',
  'UndercarriageSevereRust',
  'UndercarriageWaterSplash',
] as const;
